# Generated by Django 4.0.5 on 2022-06-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upload',
            new_name='updated',
        ),
    ]
